# Generated by Django 4.2.5 on 2023-11-25 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GenAI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='password',
            new_name='Password',
        ),
    ]
